### ISSUE TITLE
`raw_input` not defined when attempting to download pack via tool

### ISSUE THREAD

**Issue by flit** [pyocd/cmsis-pack-manager#93]
Running `pack-manager cache devs STM32F401RETx` results in this exception:

```
Traceback (most recent call last):
  File "/Users/creed/projects/pyOCD-flit/venv/mac37/bin/pack-manager", line 10, in <module>
    sys.exit(main())
  File "/Users/creed/projects/pyOCD-flit/venv/mac37/lib/python3.7/site-packages/cmsis_pack_manager/pack_manager.py", line 235, in main
    args.command(args)
  File "/Users/creed/projects/pyOCD-flit/venv/mac37/lib/python3.7/site-packages/cmsis_pack_manager/pack_manager.py", line 94, in thunk
    return command(cache, **argv)
  File "/Users/creed/projects/pyOCD-flit/venv/mac37/lib/python3.7/site-packages/cmsis_pack_manager/pack_manager.py", line 148, in command_cache
    raw_input("Press Control-C to quit; Press Enter to continue")
NameError: name 'raw_input' is not defined
```

**Comment by theotherjimmy** [comment]
Hmmmm... I should do a better job of testing on python3.

**Comment by flit** [comment]
I've used `six.moves.input()` as a compatible replacement for `raw_input()`.

**Comment by theotherjimmy** [comment]
I'll do that.
